name: Build and publish

on:
  push:
    branches:
      - master
  workflow_dispatch:
    - cron:  '05 00 * * *'
  name: Download and process

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  packages: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build_pages:
    name: Fetch data, fill metadata, build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx10g
      TYPESENSE_API_KEY: ${{ secrets.TYPESENSE_API_KEY }}
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4
      - name: Install Ant, Saxon and Python
        run: |
          sudo apt-get update && sudo apt-get install  -y --no-install-recommends openjdk-11-jre-headless ant
          ./shellscripts/dl_saxon.sh
          pip install -r requirements.txt
      - name: fetch data
        run: ./shellscripts/fetch_data.sh
      - name: process data
        run: shellscripts/process_data.sh
      - name: Build
        run: ant
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: './html'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
