name: Build and publish

on:
  workflow_dispatch:
  push:
    branches:
      - main
  

jobs:
  fetch_data:
    name: Fetch data
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4
      - name: Clear all
        run: rm -rf data
      - name: fetch data
        run: |
          shellscripts/fetch_data.sh
  fill_pages:
    name: Fill pages with new data
    needs: fetch_data
    runs-on: ubuntu-latest
    steps:
      - name: Perform Checkout
        uses: actions/checkout@v4
      - name: install required libs
        run: pip install -r requirements.txt
      - name: Complete editions
        run: |
          add-attributes -g "./data/editions/*.xml" -b "https://staribacher.acdh.oeaw.ac.at"
      - name: Complete meta
        run: |
          add-attributes -g "./data/meta/*.xml" -b "https://staribacher.acdh.oeaw.ac.at"
      - name: complete indices
        run: |
          add-attributes -g "./data/indices/*.xml" -b "https://staribacher.acdh.oeaw.ac.at"
      - name: Denormalise indices
        run: |
          denormalize-indices -f "./data/editions/*.xml" -i "./data/indices/*.xml" -m ".//*[@ref]/@ref | .//*/@source" -x ".//tei:titleStmt/tei:title[@type='main']/text()"
      - name: Add dates for calendar
        run: |
          pyscripts/make_calendar_data.py
  build_pages:
    name: Publish Edition as GitHub Pages Website
    needs: fill_pages
    runs-on: ubuntu-latest
    env:
      ANT_OPTS: -Xmx10g
    steps:
    - name: Perform Checkout
      uses: actions/checkout@v4
    - name: Build
      run: |
        ant
    - name: Update Favicons
      run: pyscripts/update_favicons.py
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./html
